---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: nginxm2ssi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: imaneaabouche/nginxm2ssi:v1
        name: nginxm2ssi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: nginxm2ssi
spec:
  ports:
  - nodePort: 32225
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
