---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: app-m2ssi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: imaneaabouche/app-m2ssi:v1
        name: app-m2ssi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: app-m2ssi
spec:
  ports:
  - nodePort: 32226
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
